name: Backend CI Pipeline

on:
  push:
    branches: [ "main" ] 
  pull_request:
    branches: [ "main" ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Install uv
      uses: astral-sh/setup-uv@v3

    - name: Set up Python 3.12
      run: uv python install 3.12

 
    - name: Run Tests
      env:
        OPENELECTRICITY_API_KEY: ${{ secrets.OPENELECTRICITY_API_KEY }}
      run: uv run pytest
